sudo: false
dist: xenial
language: python
notifications:
  email: false

python:
    - "3.6"
    - "3.7"
    - "3.8-dev"

before_install:
    - pip --no-cache install -U pip setuptools

install:
    - pip install ".[docs, tests]"

script:
    - python -m unittest discover -s tests && echo "TODO: Build docs"

after_success:
    - echo "TODO: Upload docs"
