language: python

python:
    - "3.6"

before_install:
    - pip install pipenv && pipenv install -d --skip-lock && pipenv shell;

install:
    - pip install travis-sphinx && python setup.py install;

script:
    - travis-sphinx build --nowarn --source=doc;

after_success:
    - travis-sphinx deploy
